// <auto-generated />
using HealthcareApplications.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HealthcareApplications.Migrations.User
{
    [DbContext(typeof(UserContext))]
    [Migration("20210319203101_UserContextCreate")]
    partial class UserContextCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HealthcareApplications.Models.UserModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountStatus")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SecurityQuestionIndex1")
                        .HasColumnType("int");

                    b.Property<int>("SecurityQuestionIndex2")
                        .HasColumnType("int");

                    b.Property<int>("SecurityQuestionIndex3")
                        .HasColumnType("int");

                    b.Property<string>("SecurityQuestionResponse1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityQuestionResponse2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityQuestionResponse3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
